// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrA1IX7jCJbUG6Zsw_hXX0aGfMZQHVhzQ',
    appId: '1:263087529769:web:0b4717be1c2f5d1a256138',
    messagingSenderId: '263087529769',
    projectId: 'e-commerce-app-c0fbf',
    authDomain: 'e-commerce-app-c0fbf.firebaseapp.com',
    storageBucket: 'e-commerce-app-c0fbf.firebasestorage.app',
    measurementId: 'G-HWF4EHWCZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHcTM4dkTzyvYUdqCzqqA1vItyP9O0wE4',
    appId: '1:263087529769:android:0a9e677e1d184aca256138',
    messagingSenderId: '263087529769',
    projectId: 'e-commerce-app-c0fbf',
    storageBucket: 'e-commerce-app-c0fbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKzYKoewR1G01W5Aqnn6wq846poxzOpGk',
    appId: '1:263087529769:ios:736277390ce37a58256138',
    messagingSenderId: '263087529769',
    projectId: 'e-commerce-app-c0fbf',
    storageBucket: 'e-commerce-app-c0fbf.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKzYKoewR1G01W5Aqnn6wq846poxzOpGk',
    appId: '1:263087529769:ios:736277390ce37a58256138',
    messagingSenderId: '263087529769',
    projectId: 'e-commerce-app-c0fbf',
    storageBucket: 'e-commerce-app-c0fbf.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrA1IX7jCJbUG6Zsw_hXX0aGfMZQHVhzQ',
    appId: '1:263087529769:web:d615e06efb97759e256138',
    messagingSenderId: '263087529769',
    projectId: 'e-commerce-app-c0fbf',
    authDomain: 'e-commerce-app-c0fbf.firebaseapp.com',
    storageBucket: 'e-commerce-app-c0fbf.firebasestorage.app',
    measurementId: 'G-40TJFXS3JD',
  );
}
